[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "8gnNshfwAdJ5CxT591neRLwdZ2yjmuMnJFwqFVNy2uqQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kj_dv/.config/solana/local.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
